import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Supabase Edge Functions run on Deno (npm: imports, Deno globals) — not
    // part of the Next/Node lint surface.
    "supabase/functions/**",
    // Generated by `npm run test:coverage` (gitignored, not ours to lint).
    "coverage/**",
    // Claude Code background-agent worktrees: full checkouts (with their own
    // node_modules) that appear under .claude/ while a task session runs.
    // Linting them triples the surface and fails on vendored code.
    ".claude/**",
  ]),
]);

export default eslintConfig;
